### PR TITLE
Re-encode docs/sfx.txt to UTF-8

### LINKED ISSUE #1: /docs/sfx.txt is unreadable
Reading whatever DOS codepage this file was originally saved as as Unicode apparently doesn't agree with it.

### PR DESCRIPTION
**Pull request by Neo-Desktop**
This PR will make the SFX registers documentation legible in modern browsers.

Command used to generate the aforementioned output:
`iconv -f IBM850 -t UTF-8 -o sfx.utf8.txt sfx.txt && mv sfx.utf8.txt sfx.txt`

Closes #1 

Thanks!

### CODE REVIEW

**Review by RandalLinden — APPROVED** [review]

**Comment by RandalLinden** [comment]
Thanks for taking care of this!

**Comment by bmoscon** [comment]
@RandalLinden did you mean to merge this (as opposed to closing it)?

**Comment by RandalLinden** [comment]
@bmoscon Yes... I want to merge into the main branch.

I'm a GitHub newbit so I'm guessing I didn't do it correctly?

Rand.

**Comment by bmoscon** [comment]
@RandalLinden no worries, there should be a merge button, thats what you need to select

**Comment by RandalLinden** [comment]
@bmoscon Thanks for the help with my first GitHub merge :-)

**Pull request merged**
